apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
controller:
  image:
    registry: kotara2905/ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
        type: NodePort
    nodePorts:
      http: 31080
      https: 31443
      tcp:
        8080: 32808