apiVersion : apps/v1
kind: Ingress
metadata:
  name: ingress
  namespace: nginx-ingress
spec:
  controller:
    image:
      pullPolicy: IfNotPresent
      repository: kotara2905/ingress:lates
    ingressClass: nginx
    kind: deployment
    nginxplus: false
    replicaCount: 1