apiVersion : apps/v1
kind: Pod
metadata:
  name: ingress
  labels:
    app  : ingress
    env  : prod
    owner: kot
spec:
  containers:
    - name : ingress
      image: "kotara2905/ingress:lates"
  nodeSelector:
    disktype: ingress