apiVersion : apps/v1
kind: Deployment
metadata:
  name: ingress
spec:
  selector:
    matchLabels:
      project: ingress
  template:
    metadata:
      labels:
        project: ingress
    spec:
      containers:
        - name : ingress
          image: "kotara2905/ingress:lates"
          ports:
            - containerPort: 80
      nodeSelector:
        disktype: ingress