apiVersion: v1
kind: Pod
metadata:
  name: ingress
spec:
  containers:
    - name : ingress
      image: "kotara2905/ingress:lates"
      ports:
          - containerPort: 80
          - containerPort: 443
  nodeSelector:
    disktype: ingress