apiVersion : apps/v1
kind: Ingress
metadata:
  name: ingress
spec:
  controller:
    image:
      pullPolicy: IfNotPresent
      repository: nginx/nginx-ingress
      tag: 3.0.0-ubi
    ingressClass: nginx
    kind: deployment
    nginxplus: false
    replicaCount: 1